name: Linux_Container_Workflow
run-name: ${{ github.actor }} ejecutó el workflow
on:
  push:
    branches:
      - feature/nttdata-test
      - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        # # Login en Azure
        # - name: 'Login via Azure CLI'
        #   uses: azure/login@v1
        #   with:
        #     creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nttjavatest:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nttjavatest:${{ github.sha }}
        
        # - name: Set Kubernetes context
        #   run: |
        #     az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_NAME }}

        # - name: Set Kubernetes context
        #   run: |
        #     az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_NAME }}
        
        # - name: Deploy to AKS
        #   run: |
        #     kubectl apply -f deployment.yaml
        #     kubectl apply -f service.yaml